# -*- coding: utf-8 -*-
"""nlpExtractors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g1H3Lxq6SQbQFSPaGLpIWGI_8yOfMAlG

# Importações
"""

!pip install yake
!pip install rake-nltk
!pip install keybert
!pip install multi_rake
!pip install spacy

from keybert import KeyBERT
import pandas as pd
import yake
from rake_nltk import Rake
from nltk.corpus import stopwords
import nltk
from multi_rake import Rake
import spacy.cli
import spacy

from rake_nltk import Rake
from nltk.corpus import stopwords
import nltk

nltk.download("stopwords")
nltk.download('punkt')

"""# Extração de palabras chave"""

#yake

kw_extractor = yake.KeywordExtractor()
language = "pt"
max_ngram_size = 3
deduplication_threshold = 0.9
numOfKeywords = 20
custom_kw_extractor = yake.KeywordExtractor(lan=language, n=max_ngram_size, dedupLim=deduplication_threshold, top=numOfKeywords, features=None)

text = """você pode me dizer se posso registrar duas contas com um único endereço de e-mail?"""
keywords = custom_kw_extractor.extract_keywords(text)


for kw in keywords:
  print(kw)

#rake nltk
#tive que ler um pouco na net para codar pois os exemplos na net estão desatualizados, aparentemente. então talvez esse modelo possa ter uma precisão melhor e eu não sei

pt_stp_words = stopwords.words('portuguese')
rake_nltk_var = Rake()

text = """eu estou com um problema em relação a transporadora. Preciso de ajuda com esse problema."""

rake_nltk_var.extract_keywords_from_text(text)
keyword_extracted = rake_nltk_var.get_ranked_phrases()

print(keyword_extracted)

#keybert

doc = """
eu estou com um problema em relação a transporadora. Preciso de ajuda com esse problema.
      """
kw_model = KeyBERT()
keywords = kw_model.extract_keywords(doc)


kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 1), stop_words='portuguese')

print(keywords)
keywords = kw_model.extract_keywords(doc, highlight=True)

# mult-rake
from multi_rake import Rake

doc = (
    'eu estou com um problema em realação a transporadora. Preciso de ajuda com esse problema.'
)

rake = Rake()

keywords = rake.apply(doc)

print(keywords[:10])

#spacy
#n funfa em pt mesmo com o modelo em português??

spacy.cli.download("pt_core_news_lg")


nlp = spacy.load("pt_core_news_sm")
text = """eu estou com um problema em realação a transporadora. Preciso de ajuda com esse problema."""
doc = nlp(text)
print(doc.ents)

def keybert_get_kw(doc):
  doc = doc
  kw_model = KeyBERT()
  keywords = kw_model.extract_keywords(doc)
  kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 1), stop_words='portuguese', use_maxsum=True, diversity=0.7)

  keywords = kw_model.extract_keywords(doc)
  print(keywords)

def mult_rake_get_kw(doc):
  from multi_rake import Rake
  text = doc
  rake = Rake(max_words=1, language_code='pt')
  keywords = rake.apply(text)

  print(keywords)

def rake_nltk_get_kw(doc):

  pt_stp_words = stopwords.words('portuguese')
  rake_nltk_var = Rake()

  text = doc

  rake_nltk_var.extract_keywords_from_text(text)
  keyword_extracted = rake_nltk_var.get_ranked_phrases()

  print(keyword_extracted)

def yake_get_kw(doc):

  kw_extractor = yake.KeywordExtractor()
  language = "pt"
  max_ngram_size = 1
  deduplication_threshold = 0.9
  numOfKeywords = 20
  custom_kw_extractor = yake.KeywordExtractor(lan=language, n=max_ngram_size, dedupLim=deduplication_threshold, top=numOfKeywords, features=None)

  text = doc
  keywords = custom_kw_extractor.extract_keywords(text)

  print(keywords)

df = pd.read_csv('emails - Página1.csv')

df

i = 0
  while i != 10:

    doc = df['emails'][i]

    #printar a extração de keywords de cada um dos modelos
    mult_rake_get_kw(doc)
    keybert_get_kw(doc)
    yake_get_kw(doc)
    rake_nltk_get_kw(doc)

    print('-')
    i+=1

"""**Testando cada modelo com base em categorias de Email**
*pagamentos
*

Usando Multi-Rake, Keybert, Yake, Rake-nltk

foram configurados para extrair uma única palavra chave, não keyphrases com uma ou mais palavras.
"""

i = 0
  while i != 4:

    doc = ["eu quero ver suas opções de pagamento, você pode me ajudar?", "você pode me dizer se eu posso fazer um pagamento com cartão?", "onde posso ver suas opções de pagamento?", "onde verificar suas formas de pagamento?", "como posso ver seus métodos de pagamento?"];

    #printar a extração de keywords de cada um dos modelos
    mult_rake_get_kw(doc[i])
    keybert_get_kw(doc[i])
    yake_get_kw(doc[i])
    rake_nltk_get_kw(doc[i])

    print('-')
    i+=1

#emails baseado em compra, pedidos
  i = 0
  while i != 10:

    doc = [
      "Eu quero cancelar um pedido, o que devo fazer?",
      "Eu preciso de ajuda para cancelar uma compra",
      "Posso cancelar uma compra?",
      "Eu quero cancelar uma compra, você pode me ajudar?",
      "Eu quero cancelar uma compra, o que tenho que fazer?",
      "Eu quero cancelar um pedido",
      "Você pode pedir á alguém para cancelar uma compra, por favor?",
      "Como cancelar um pedido",
      "Eu quero cancelar um pedido, o que tenho que fazer?",
      "Peça alguém para cancelar um pedido"
    ];

    #printar a extração de keywords de cada um dos modelos
    mult_rake_get_kw(doc[i])
    keybert_get_kw(doc[i])
    yake_get_kw(doc[i])
    rake_nltk_get_kw(doc[i])

    print('-')
    i+=1

#emails baseados em contato, entrar em contato
  i = 0
  while i != 10:

    doc = [
      "Preciso de informações e quero entrar em contato com o suporte ao cliente",
      "Eu quero entrar em contato com o suporte ao cliente",
      "Preciso de informações sobre o endereço de e-mail do suporte ao cliente",
      "Preciso de informações, o que devo fazer para ligar para o atendimento ao cliente?",
      "Ligue para o atendimento ao cliente",
      "Você pode me dizer o e -mail para entrar em contato com o suporte ao cliente, por favor?",
      "Pergunte a um agente como falar com o atendimento ao cliente",
      "Quero informações, como posso entrar em contato com o suporte ao cliente?",
      "Você pode me dizer o NBUMBER do atendimento ao cliente?",
      "Como falar com o atendimento ao cliente",
    ];

    #printar a extração de keywords de cada um dos modelos
    mult_rake_get_kw(doc[i])
    keybert_get_kw(doc[i])
    yake_get_kw(doc[i])
    rake_nltk_get_kw(doc[i])

    print('-')
    i+=1

#conta, perfil
  i = 0
  while i != 10:

    doc = [
    "Não tenho perfil, como posso criar um?",
    "Queria uma conta de usuário, como posso abrir uma?",
    "Não tenho conta, você pode me ajudar?",
    "Quero saber se posso criar mais de uma conta com o mesmo endereço de e-mail",
    "Não tenho uma conta, o que posso fazer para abrir uma?",
    "Quero saber se posso criar duas contas com um único endereço de e-mail",
    "Eu quero uma conta, crie uma",
    "Eu quero uma conta, você pode criar uma?",
    "Eu não tenho uma conta, posso criar uma?",
    "Eu não tenho uma conta, você pode abrir uma?"
    ];

    #printar a extração de keywords de cada um dos modelos
    mult_rake_get_kw(doc[i])
    keybert_get_kw(doc[i])
    yake_get_kw(doc[i])
    rake_nltk_get_kw(doc[i])

    print('-')
    i+=1

#entrega, endereço de entrega
  i = 0
  while i != 10:

    doc = [
      "Eu quero modificar meu endereço de entrega, o que devo fazer?",
      "Quero atualizar meu endereço de entrega, o que posso fazer?",
      "Onde posso editar meu endereço de entrega?",
      "Você pode perguntar a um agente onde posso atualizar meu endereço de entrega?",
      "Posso fazer alterações no meu endereço de entrega?",
      "Meu endereço de entrega mudou, o que pode IDO?",
      "Como edito meu endereço de entrega?",
      "Onde eu mudo meu endereço de entrega?",
      "você pode perguntar a um agente como posso alterar meu endereço de entrega?",
      "Quero modificar meu endereço de entrega, você pode me ajudar?"
    ];

    #printar a extração de keywords de cada um dos modelos
    mult_rake_get_kw(doc[i])
    keybert_get_kw(doc[i])
    yake_get_kw(doc[i])
    rake_nltk_get_kw(doc[i])

    print('-')
    i+=1

#ingressos, entrega
  i = 0
  while i != 10:

    doc = [
      "Pergunte a alguém como posso ver as opções para entrega de ingressos",
      "Como faço para ver as opções de entrega?",
      "Você pode me falar sobre as opções de entrega de ingressos?",
      "Eu quero ver as opções de entrega",
      "Você pode me mostrar as opções de entrega de ingressos?",
      "você pode perguntar a um agente onde posso verificar as opções para entrega de ingressos?",
      "Quero verificar as opções de entrega, o que devo fazer?",
      "Eu quero ver as opções de entrega, você pode me ajudar?",
      "Você pode pedir a um agente que me mostre as opções de entrega?",
      "Por favor, pergunte a um agente se posso verificar as opções para entrega de ingressos"
    ];

    #printar a extração de keywords de cada um dos modelos
    mult_rake_get_kw(doc[i])
    keybert_get_kw(doc[i])
    yake_get_kw(doc[i])
    rake_nltk_get_kw(doc[i])

    print('-')
    i+=1